[package]
name = "vndf-server"
version = "0.0.1"
authors = ["Hanno Braun <mail@hannobraun.de>"]


[dependencies]
env_logger = "*"
log        = "*"
time       = "*"

[dependencies.shared]
path = "../shared"
