[package]
name    = "test-suite"
version = "0.1.0"
authors = [ "mail@hannobraun.de" ]


[dependencies.rustecs]
path = "../librustecs"

[dependencies.rustecs_macros]
path = "../librustecs_macros"

[dependencies.vndf]
path = "../vndf"
