[package]

name = "client_ng"
version = "0.0.1"
authors = ["Hanno Braun <mail@hannobraun.de>"]

[lib]
name = "client"
path = "src/lib/lib.rs"

[[bin]]
name = "vndf-client-ng"


[dependencies.acpe]
git = "https://github.com/hannobraun/acpe.git"

[dependencies.common]
path = "../common"
