[package]
name    = "test_suite"
version = "0.0.1"
authors = ["Hanno Braun <mail@hannobraun.de>"]


[dependencies]
rand = "*"
time = "*"

[dependencies.client]
path = "../client"

[dependencies.common]
path = "../common"

[dependencies.game_service]
path = "../game_service"
