[package]
name    = "test_suite"
version = "0.0.1"
authors = ["Hanno Braun <mail@hannobraun.de>"]


[dependencies]
nalgebra = "*"
rand     = "*"
time     = "*"

[dependencies.client]
path = "../client"

[dependencies.common]
path = "../shared"

[dependencies.server]
path = "../server"
