[package]
name    = "vndf"
version = "0.1.0"
authors = [ "mail@hannobraun.de" ]

[[bin]]
name = "vndf-client"
test = false

[[bin]]
name = "vndf-game-service"
test = false


[dependencies.client]
path = "../client"

[dependencies.game_service]
path = "../game_service"

[dependencies.test_infra]
path = "../test_infra"

[dependencies.test_tools]
path = "../test_tools"
