[package]
name    = "vndf"
version = "0.1.0"
authors = [ "mail@hannobraun.de" ]

[[bin]]
name = "vndf-client"
test = false

[[bin]]
name = "vndf-game-service"
test = false

[lib]
name = "vndf"
test = false


[dependencies.client]
path = "../client"

[dependencies.epoll]
path = "../epoll"

[dependencies.game]
path = "../game"

[dependencies.net]
path = "../net"

[dependencies.physics]
path = "../physics"

[dependencies.platform]
path = "../platform"

[dependencies.platform_cli]
path = "../platform_cli"

[dependencies.platform_desktop]
path = "../platform_desktop"

[dependencies.protocol]
path = "../protocol"

[dependencies.rustecs]
path = "../librustecs"

[dependencies.rustecs_macros]
path = "../librustecs_macros"

[dependencies.test_infra]
path = "../test_infra"

[dependencies.test_tools]
path = "../test_tools"
