[package]
name    = "vndf"
version = "0.1.0"
authors = [ "mail@hannobraun.de" ]

[[bin]]
name = "vndf-client"
test = false

[[bin]]
name = "vndf-game-service"
test = false

[[lib]]
name = "vndf"
test = false


[dependencies.epoll]
path = "../epoll"

[dependencies.net]
path = "../net"

[dependencies.physics]
path = "../physics"

[dependencies.rustecs]
path = "../librustecs"

[dependencies.rustecs_macros]
path = "../librustecs_macros"


[dependencies.gl]
path = "../../../vendor/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.freetype]
path = "../../../vendor/rust-freetype"

[dependencies.stb_image]
path = "../../../vendor/rust-stb-image"
