[package]
name    = "rocks"
version = "0.1.0"
authors = [ "mail@hannobraun.de" ]


[dependencies.iron]
git = "https://github.com/iron/iron.git"

[dependencies.static_file]
git = "https://github.com/hannobraun/static-file.git"
