[package]

name = "client"
version = "0.0.1"
authors = ["Hanno Braun <mail@hannobraun.de>"]

[lib]
name = "client"
path = "src/lib/lib.rs"

[[bin]]
name = "vndf-client"


[dependencies]
getopts         = "*"
nalgebra        = "*"
rustc-serialize = "*"
time            = "*"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs.git"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs.git"

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx_macros.git"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin.git"

[dependencies.common]
path = "../common"
