[package]
name    = "client"
version = "0.1.0"
authors = [ "mail@hannobraun.de" ]

[lib]
name = "client"

[[bin]]
name = "vndf-client"


[dependencies.game]
path = "../game"

[dependencies.platform]
path = "../platform"

[dependencies.platform_cli]
path = "../platform_cli"

[dependencies.platform_desktop]
path = "../platform_desktop"

[dependencies.protocol]
path = "../protocol"
